export const TOOLS = {
  policy: {
    id:"policy", icon:"📋", name:"PolicySaathi",
    fullName:"PolicySaathi — Insurance Decoder",
    role:"Paste your LIC / Health / Term / ULIP / Endowment policy text below",
    badge:"IRR · Exclusions · Red Flags", badgeClass:"pill-red",
    prompts:["LIC Jeevan Anand — is it worth it?","My health policy has a 2-year waiting period clause","ULIP with 5% annual charges — good or bad?","Term policy claim rejection — is it valid?"],
    greeting:`<h3>👋 Namaste! Let's decode your policy.</h3>Upload a PDF or paste policy text. I'll check against <strong>latest IRDAI regulations</strong>:<ul><li>Real return (IRR/XIRR) vs advertised</li><li>Every exclusion in plain language</li><li>Claim-rejection red flag clauses</li><li>Good value or not — I'll be direct</li></ul><div class="section-box">💡 Try: "LIC Jeevan Anand, 25 years, ₹10L sum assured, ₹45,000 annual premium"</div>`,
  },
  loan: {
    id:"loan", icon:"🏦", name:"LoanLens",
    fullName:"LoanLens — Loan Cost Decoder",
    role:"Paste your loan sanction letter, EMI schedule, or loan agreement",
    badge:"APR · Hidden Fees · RBI Rights", badgeClass:"pill-gold",
    prompts:["Home loan sanction letter — check my APR","Processing fee 1% — is this normal?","Bank wants to bundle insurance with my loan","Can I prepay without penalty?"],
    greeting:`<h3>🏦 Let's find your loan's real cost.</h3>Upload a PDF or paste your loan agreement. Checked against <strong>latest RBI guidelines</strong>:<ul><li>True APR vs headline rate</li><li>Every hidden fee in ₹</li><li>Total interest over full tenure</li><li>Your RBI borrower rights</li></ul><div class="section-box">💡 Try: "SBI home loan, ₹50L, 20 years, 8.5%, ₹15,000 processing fee"</div>`,
  },
  flat: {
    id:"flat", icon:"🏗️", name:"FlatTruth",
    fullName:"FlatTruth — Builder Agreement Decoder",
    role:"Paste your builder-buyer agreement, allotment letter, or sale deed",
    badge:"RERA · Clauses · True Cost", badgeClass:"pill-red",
    prompts:["Builder is charging PLC, EDC, IDC — what are these?","Possession date clause seems vague","Builder can change specs unilaterally?","What are my RERA rights?"],
    greeting:`<h3>🏗️ Let's see what that agreement really says.</h3>Upload a PDF or paste the agreement. Checked against <strong>latest RERA rules</strong>:<ul><li>Every buyer-unfriendly clause with clause number</li><li>True total cost including all hidden charges</li><li>Whether your RERA rights are being waived</li></ul><div class="section-box">💡 Try: builder name, location, price, possession date, penalty clauses.</div>`,
  },
  mf: {
    id:"mf", icon:"📈", name:"MutualMirror",
    fullName:"MutualMirror — Mutual Fund Decoder",
    role:"Paste your CAMS / NSDL Consolidated Account Statement (CAS)",
    badge:"XIRR · Commission Leakage", badgeClass:"pill-green",
    prompts:["Am I in regular or direct plans?","How much commission is my distributor earning?","Too many funds in my portfolio?","Calculate my real XIRR"],
    greeting:`<h3>📈 Let's see your portfolio's real performance.</h3>Upload your CAS PDF or paste the text. Using live <strong>AMFI/SEBI data</strong>:<ul><li>Real XIRR for each fund</li><li>Regular vs Direct plan commission leakage in ₹</li><li>Portfolio overlap and redundancy</li><li>Expense ratio drag over 10/20 years</li></ul><div class="section-box">💡 Try: "Axis Bluechip ₹1L, HDFC Midcap ₹50K, invested Jan 2021"</div>`,
  },
  salary: {
    id:"salary", icon:"💼", name:"SalaryScan",
    fullName:"SalaryScan — Offer Letter Decoder",
    role:"Paste your job offer letter or CTC breakup",
    badge:"In-Hand · Old vs New Regime", badgeClass:"pill-gold",
    prompts:["My CTC is ₹12L but take-home seems low","Old regime or new — which saves more?","Joining bonus with 1-year clawback","What are notional components?"],
    greeting:`<h3>💼 Let's find your real take-home salary.</h3>Upload a PDF or paste your offer letter. Calculated with <strong>current FY Income Tax slabs</strong>:<ul><li>Exact monthly in-hand after all deductions</li><li>Old vs New Regime — exact ₹ savings</li><li>At-risk and notional components flagged</li><li>Clawback and lock-in clauses</li></ul><div class="section-box">💡 Try: "₹12L CTC, Basic ₹4.8L, HRA ₹2.4L, Special Allowance ₹3L"</div>`,
  },
  bill: {
    id:"bill", icon:"🏥", name:"BillBreaker",
    fullName:"BillBreaker — Hospital Bill Decoder",
    role:"Paste your hospital bill, discharge summary, or insurance rejection letter",
    badge:"Overcharging · CGHS · Dispute", badgeClass:"pill-red",
    prompts:["Insurance rejected my cashless claim","Hospital charged consumables separately","Same procedure billed twice?","I want to dispute this bill"],
    greeting:`<h3>🏥 Let's check if you were overcharged.</h3>Upload a PDF or paste the bill. Checked against <strong>CGHS 2023 rates and IRDAI guidelines</strong>:<ul><li>Line-by-line vs CGHS benchmark rates</li><li>Duplicate billing and unjustified charges</li><li>Insurance rejection validity</li><li>Ready-to-send dispute letter</li></ul><div class="section-box">💡 Describe: hospital, procedure, total amount, insurer, rejection reason.</div>`,
  },
};
